### ISSUE TITLE
Unable to get Metadata info of the file. 

### ISSUE THREAD

**Issue by Dpkkmr** [mgcrea/node-mediainfo-parser#4]
When I try to get metadata information, I get below mention error: 

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: spawn mediainfo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:379:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

Test Environment Details:
Operation System: Windows 8
Node Version : 9.11.0
npm version: 5.6

**Comment by rafalpawlow** [comment]
Have you installed mediainfo CLI?
